### ISSUE TITLE
Error in Rendering functional_plant_indicators_wetland 

### ISSUE THREAD

**Issue by DrMattG** [NINAnor/ecosystemCondition#71]
In finctional_plant_indicators_wetland.rmd I get this error at Line 1354:

_Error in density.default(res.wetland[res.wetland$fp_ind == "pH1" & res.wetland$fp_ind == :
argument 'x' must be numeric_

It looks like the column "original" no longer exists in the dataframe. 

https://github.com/NINAnor/ecosystemCondition/blob/d28f4d80b463739cf58fffdee1b4fe16a1ec5d7d/functional_plant_indicators_wetland.Rmd#L1354C1-L1354C131

@joatop can you provide a fix please

**Comment by joatop** [comment]
@DrMattG 
I forgot to add the code that creates the 'original'-column. And line 1352 should thus have thrown the same error, too.

To fix this, lines 1141 - 1159 need to be replaced with the following code:

#### getting scaled AND original values ####
res.wetland <- results.wetland[['2-sided']]

# make long version of the scaled value part
res.wetland <-
  res.wetland %>% 
  pivot_longer(
    cols = c("Light1","Light2","Moist1","Moist2","pH1","pH2","Nitrogen1","Nitrogen2"),
    names_to = "fp_ind",
    values_to = "scaled_value",
    values_drop_na = TRUE
  )

# add original values as well
res.wetland <- 
  res.wetland %>% add_column(original = results.wetland[['original']] %>% 
                               pivot_longer(
                                 cols = c("Light1","Light2","Moist1","Moist2","pH1","pH2","Nitrogen1","Nitrogen2"),
                                 names_to = NULL,
                                 values_to = "original",
                                 values_drop_na = FALSE
                               ) %>%
                               pull(original)
  )


In addition, pls change the text in line 1138 to:
"In order to visualize the results we need to rearrange the results-objects from wide to long format (note that there is both a lower and an upper condition indicator for each of the functional plant indicators)."

**Comment by DrMattG** [comment]
Thanks! Fixed with #73
